<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version1 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('articles', array(
             'id' => 
             array(
              'type' => 'integer',
              'unsigned' => '1',
              'primary' => '1',
              'autoincrement' => '1',
              'comment' => 'Идентификатор',
              'length' => '4',
             ),
             'title' => 
             array(
              'type' => 'string',
              'comment' => 'Название',
              'length' => '125',
             ),
             'version' => 
             array(
              'unsigned' => '1',
              'notnull' => '1',
              'default' => '1',
              'comment' => 'Версия',
              'type' => 'integer',
              'length' => '4',
             ),
             'creator_id' => 
             array(
              'unsigned' => '1',
              'comment' => 'Создал',
              'type' => 'integer',
              'length' => '4',
             ),
             'editor_id' => 
             array(
              'unsigned' => '1',
              'comment' => 'Последним изменил',
              'type' => 'integer',
              'length' => '4',
             ),
             'datetime_created' => 
             array(
              'type' => 'timestamp',
              'length' => '25',
             ),
             'datetime_edited' => 
             array(
              'type' => 'timestamp',
              'length' => '25',
             ),
             'deleted' => 
             array(
              'unsigned' => '1',
              'notnull' => '1',
              'default' => '0',
              'comment' => 'Удалено',
              'type' => 'integer',
              'length' => '1',
             ),
             'status' => 
             array(
              'unsigned' => '1',
              'notnull' => '1',
              'default' => '0',
              'comment' => 'Статус',
              'type' => 'integer',
              'length' => '1',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('articles');
    }
}