<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version2 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('articles', 'articles_creator_id_editors_id', array(
             'name' => 'articles_creator_id_editors_id',
             'local' => 'creator_id',
             'foreign' => 'id',
             'foreignTable' => 'editors',
             'onUpdate' => 'cascade',
             'onDelete' => 'set null',
             ));
        $this->createForeignKey('articles', 'articles_editor_id_editors_id', array(
             'name' => 'articles_editor_id_editors_id',
             'local' => 'editor_id',
             'foreign' => 'id',
             'foreignTable' => 'editors',
             'onUpdate' => 'cascade',
             'onDelete' => 'set null',
             ));
        $this->addIndex('articles', 'articles_creator_id', array(
             'fields' => 
             array(
              0 => 'creator_id',
             ),
             ));
        $this->addIndex('articles', 'articles_editor_id', array(
             'fields' => 
             array(
              0 => 'editor_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('articles', 'articles_creator_id_editors_id');
        $this->dropForeignKey('articles', 'articles_editor_id_editors_id');
        $this->removeIndex('articles', 'articles_creator_id', array(
             'fields' => 
             array(
              0 => 'creator_id',
             ),
             ));
        $this->removeIndex('articles', 'articles_editor_id', array(
             'fields' => 
             array(
              0 => 'editor_id',
             ),
             ));
    }
}