<?php

/**
 * Статьи.
 *
 * This class has been auto-generated by the Doctrine ORM Framework.
 */
class Articles extends BaseArticles
{
    public static $nameSingular = 'Статья';
    public static $namePlural = 'Статьи';
}
