<?php

/**
 * Files.
 *
 * This class has been auto-generated by the Doctrine ORM Framework.
 */
class Files extends BaseFiles implements ZfeFiles_FileInterface
{
    public function getPathHelper(): ZfeFiles_PathHelper_Abstract
    {
        return new ZfeFiles_PathHelper_Default($this);
    }

    public function getDataForUploader(): array
    {
        return [
            'id' => $this->id,
            'name' => $this->title,
            'previewUrl' => $this->getPreviewUrl(),
            'downloadUrl' => $this->getDownloadUrl(),
        ];
    }

    public function getPreviewUrl(): string
    {
        return $this->getDownloadUrl();
        return '/' . static::getControllerName() . '/preview/id/' . $this->id;
    }

    public function getDownloadUrl(): string
    {
        return '/' . static::getControllerName() . '/download/id/' . $this->id;
    }

    public static function getUploadUrl(): string
    {
        return '/' . static::getControllerName() . '/upload';
    }
}
